{{- if .Values.haproxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haptic.fullname" . }}-haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  {{- with .Values.haproxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.haproxy.service.type }}
  {{- if .Values.haproxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.haproxy.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.haproxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.haproxy.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.haproxy.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.haproxy.service.loadBalancerClass }}
  {{- end }}
  {{- if .Values.haproxy.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.haproxy.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.haproxy.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.haproxy.service.internalTrafficPolicy }}
  {{- end }}
  {{- if .Values.haproxy.service.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.haproxy.service.healthCheckNodePort }}
  {{- end }}
  {{- if .Values.haproxy.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ .Values.haproxy.service.publishNotReadyAddresses }}
  {{- end }}
  selector:
    {{- include "haptic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  ports:
    - name: http
      port: {{ .Values.haproxy.service.http.port }}
      targetPort: http
      protocol: TCP
      {{- if or (eq .Values.haproxy.service.type "NodePort") (eq .Values.haproxy.service.type "LoadBalancer") }}
      nodePort: {{ .Values.haproxy.service.http.nodePort }}
      {{- end }}
    - name: https
      port: {{ .Values.haproxy.service.https.port }}
      targetPort: https
      protocol: TCP
      {{- if or (eq .Values.haproxy.service.type "NodePort") (eq .Values.haproxy.service.type "LoadBalancer") }}
      nodePort: {{ .Values.haproxy.service.https.nodePort }}
      {{- end }}
    - name: stats
      port: {{ .Values.haproxy.service.stats.port }}
      targetPort: stats
      protocol: TCP
      {{- if or (eq .Values.haproxy.service.type "NodePort") (eq .Values.haproxy.service.type "LoadBalancer") }}
      nodePort: {{ .Values.haproxy.service.stats.nodePort }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haptic.fullname" . }}-haproxy-dataplane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
spec:
  type: {{ .Values.haproxy.dataplane.service.type }}
  selector:
    {{- include "haptic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  ports:
    - name: dataplane
      port: {{ .Values.haproxy.ports.dataplane }}
      targetPort: dataplane
      protocol: TCP
{{- end }}
