{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "haptic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "haptic.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "haptic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
