apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haptic.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
type: Opaque
data:
  # Production dataplane credentials
  dataplane_username: {{ .Values.credentials.dataplane.username | b64enc | quote }}
  dataplane_password: {{ .Values.credentials.dataplane.password | b64enc | quote }}
