apiVersion: v2
name: haptic
description: HAPTIC - HAProxy Template Ingress Controller
type: application
version: 0.1.0-alpha.11
appVersion: "0.1.0-alpha.11"
keywords:
  - haproxy
  - ingress
  - controller
  - loadbalancer
  - template
home: https://gitlab.com/haproxy-haptic/haptic
sources:
  - https://gitlab.com/haproxy-haptic/haptic
maintainers:
  - name: phihos
annotations:
  # Document all component images (Artifact Hub standard)
  artifacthub.io/images: |
    - name: controller
      image: registry.gitlab.com/haproxy-haptic/haptic:0.1.0-alpha.11
      platforms:
        - linux/amd64
        - linux/arm64
    - name: haproxy
      image: haproxytech/haproxy-debian:3.2
      platforms:
        - linux/amd64
        - linux/arm64

  # License
  artifacthub.io/license: Apache-2.0

  # Changelog
  artifacthub.io/changes: |
    - kind: added
      description: HAProxy Ingress annotation compatibility with 47 annotations
    - kind: changed
      description: HAProxy Ingress library enabled by default
    - kind: fixed
      description: Template validator currentConfig type declaration

  # Links
  artifacthub.io/links: |
    - name: Documentation
      url: https://gitlab.com/haproxy-haptic/haptic#readme
    - name: Issue Tracker
      url: https://gitlab.com/haproxy-haptic/haptic/-/issues

  # Recommendations
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
      description: Required for webhook TLS certificate management when webhook.certManager.enabled=true

  # Minimum HAProxy version requirement
  haproxy.org/minimum-version: "3.0"
