rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
  comments:
    # Set to warning to avoid failing on existing code with inline comments
    level: warning
    min-spaces-from-content: 2
  document-end: disable
  document-start: disable
  empty-lines:
    max: 2
    max-end: 0
    max-start: 0
  key-duplicates: enable
  line-length: disable
  trailing-spaces: enable
  truthy:
    level: warning
