{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.secretName | default (printf "%s-webhook-cert" (include "haproxy-template-ic.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.webhook.secretName | default (printf "%s-webhook-cert" (include "haproxy-template-ic.fullname" .)) }}
  duration: {{ .Values.webhook.certManager.duration | default "8760h" }}
  renewBefore: {{ .Values.webhook.certManager.renewBefore | default "720h" }}
  dnsNames:
    - {{ include "haproxy-template-ic.fullname" . }}-webhook
    - {{ include "haproxy-template-ic.fullname" . }}-webhook.{{ .Release.Namespace }}
    - {{ include "haproxy-template-ic.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "haproxy-template-ic.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.webhook.certManager.createIssuer }}
    name: {{ include "haproxy-template-ic.fullname" . }}-webhook-selfsigned
    kind: Issuer
    {{- else }}
    {{- if not .Values.webhook.certManager.issuerRef.name }}
    {{- fail "webhook.certManager.issuerRef.name is required when createIssuer is false" }}
    {{- end }}
    {{- toYaml .Values.webhook.certManager.issuerRef | nindent 4 }}
    {{- end }}
  usages:
    - digital signature
    - key encipherment
    - server auth
{{- end }}
